/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagui;

import java.util.Enumeration;
import javax.swing.AbstractButton;


/**
 *
 * @author Christian
 */
public class addTask extends javax.swing.JFrame {
    private String taskName;
    private String difficulty;
    private String dueDate;
    private String dueTime;
    private final Error error;
    private TamaGuiHome home;
    
    /**
     * Creates new form addTask
     * @param tamaGuiHome
     */
    public addTask(TamaGuiHome tamaGuiHome) {
        initComponents();
        error = new Error();
        home = tamaGuiHome;
    }
    
    public addTask(TamaGuiHome tamaGuiHome, String taskName, String difficulty, String dueDate, String dueTime) {
        initComponents();
        error = new Error();
        home = tamaGuiHome;
        this.TaskName.setText(taskName);
        this.dueDateField.setText(dueDate);
        this.dueTimeField.setText(dueTime);
        this.AddTaskLabel.setText("Edit Task");
        switch (difficulty) {
            case "Easy" -> this.Easy.setSelected(true);
            case "Medium" -> this.Medium.setSelected(true);
            default -> this.Hard.setSelected(true);
        }
    }
    
    private String getSelectedDifficulty()
    {  
        Enumeration<AbstractButton> difficultyButtons = Difficulty.getElements();
        while (difficultyButtons.hasMoreElements()) {
            AbstractButton difficultyButton = difficultyButtons.nextElement();
            if (difficultyButton.isSelected()) {
                    System.out.println("Selected Difficulty: "+ difficultyButton.getText());
                    return difficultyButton.getText();
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difficulty = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskName = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        dueTimeField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dueDateField = new javax.swing.JTextPane();
        AddTaskLabel = new javax.swing.JLabel();
        DueTimeLabel = new javax.swing.JLabel();
        TaskDifficultyLabel = new javax.swing.JLabel();
        CompleteByLabel = new javax.swing.JLabel();
        Easy = new javax.swing.JCheckBox();
        Medium = new javax.swing.JCheckBox();
        Hard = new javax.swing.JCheckBox();
        AmPm = new javax.swing.JComboBox<>();
        Done = new javax.swing.JButton();
        TaskNameLabel = new javax.swing.JLabel();
        DueDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(TaskName);

        jScrollPane3.setViewportView(dueTimeField);

        jScrollPane2.setViewportView(dueDateField);

        AddTaskLabel.setText("Add Task");

        DueTimeLabel.setText("Due Time (hh:mm) :");

        TaskDifficultyLabel.setText("Choose Task Difficulty");

        CompleteByLabel.setText(" *Complete By:");

        Difficulty.add(Easy);
        Easy.setText("Easy");

        Difficulty.add(Medium);
        Medium.setText("Medium");

        Difficulty.add(Hard);
        Hard.setText("Hard");

        AmPm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        AmPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmPmActionPerformed(evt);
            }
        });

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        TaskNameLabel.setText("*Task Name");

        DueDateLabel.setText("Due Date (mm/dd/yy) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DueDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DueTimeLabel)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Done)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(TaskDifficultyLabel))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Medium)
                            .addComponent(Hard)
                            .addComponent(Easy))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(CompleteByLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(AddTaskLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTaskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaskDifficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Easy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Medium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hard)
                .addGap(1, 1, 1)
                .addComponent(CompleteByLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DueDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DueTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(AmPm))
                .addGap(18, 18, 18)
                .addComponent(Done)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Done Button
    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
       
        //Sets task Name. Pops error message if field is empty
        taskName = TaskName.getText().trim();
        if (taskName == null || taskName.isEmpty()){
            error.SetErrorMsg("Task Name is empty");
            error.setVisible(true);
            return;
        }
        difficulty = getSelectedDifficulty();
        if (difficulty == null || difficulty.isEmpty()){
            error.SetErrorMsg("Difficulty is not selected");
            error.setVisible(true);
            return;
        }
        
        dueDate = dueDateField.getText().trim();
        // TODO add proper date validation
        if (dueDate == null || dueDate.isEmpty() || (dueDate.split("/").length != 3)){
            error.SetErrorMsg("Due Date is invalid");
            error.setVisible(true);
            return;
        }
        // TODO add proper Time validation
        dueTime = dueTimeField.getText().trim();
        if (dueTime == null || dueTime.isEmpty() || (dueTime.split(":").length != 2)){
            error.SetErrorMsg("Due Time is invalid");
            error.setVisible(true);
            return;
        }
        
        Task newTask = new Task(taskName, difficulty, dueDate, dueTime);
        home.addTask(newTask);
        // Close the addTask window -- Last thing to run when "Done" is pressed.
        this.dispose();
    }//GEN-LAST:event_DoneActionPerformed

    private void AmPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmPmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmPmActionPerformed

// Set method for taskName
public  void setTaskName(String taskName){
    this.TaskName.setText(taskName);
}

    
// Get method for taskName
public String getTaskName(){
    return taskName;
}

// Get method for difficulty
public String getDifficulty() {
    return difficulty;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTaskLabel;
    private javax.swing.JComboBox<String> AmPm;
    private javax.swing.JLabel CompleteByLabel;
    private javax.swing.ButtonGroup Difficulty;
    private javax.swing.JButton Done;
    private javax.swing.JLabel DueDateLabel;
    private javax.swing.JLabel DueTimeLabel;
    private javax.swing.JCheckBox Easy;
    private javax.swing.JCheckBox Hard;
    private javax.swing.JCheckBox Medium;
    private javax.swing.JLabel TaskDifficultyLabel;
    private javax.swing.JTextPane TaskName;
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JTextPane dueDateField;
    private javax.swing.JTextPane dueTimeField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
