/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tamagui;

/**
 *
 * @author Christian
 */
public class Task extends javax.swing.JPanel {
    private final String taskName;
    private final String difficulty;
    private final String dueDate;
    private final String dueTime;
    
    /**
     * Creates new form Task
     * @param taskname
     * @param difficulty
     * @param dueDate
     * @param dueTime
     */
    public Task(String taskname, String difficulty, String dueDate, String dueTime) {
        initComponents();
        this.taskName = taskname;
        this.difficulty = difficulty;
        this.dueDate = dueDate;
        this.dueTime = dueTime;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskNameLabel = new javax.swing.JLabel();

        taskNameLabel.setText(taskName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(taskNameLabel)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(taskNameLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public  String getTaskName(){
        return this.taskName;
    }

    public  String getDifficulty(){
        return this.difficulty;
    }
    
    public  String getDueDate(){
        return this.dueDate;
    }
    public  String getDueTime(){
        return this.dueTime;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel taskNameLabel;
    // End of variables declaration//GEN-END:variables
}
